[target.aarch64-unknown-linux-musl]
pre-build = [
    "apt-get update",
    "apt-get install --assume-yes musl musl-dev musl-tools protobuf-compiler"
]

[target.arm-unknown-linux-musleabi]
pre-build = [
    "apt-get update",
    "apt-get install --assume-yes musl musl-dev musl-tools protobuf-compiler"
]

[target.arm-unknown-linux-musleabihf]
pre-build = [
    "apt-get update",
    "apt-get install --assume-yes musl musl-dev musl-tools protobuf-compiler"
]

[target.armv5te-unknown-linux-musleabi]
pre-build = [
    "apt-get update",
    "apt-get install --assume-yes musl musl-dev musl-tools protobuf-compiler"
]

[target.armv7-unknown-linux-musleabi]
pre-build = [
    "apt-get update",
    "apt-get install --assume-yes musl musl-dev musl-tools protobuf-compiler"
]

[target.armv7-unknown-linux-musleabihf]
pre-build = [
    "apt-get update",
    "apt-get install --assume-yes musl musl-dev musl-tools protobuf-compiler"
]

[target.i586-unknown-linux-musl]
pre-build = [
    "apt-get update",
    "apt-get install --assume-yes musl musl-dev musl-tools protobuf-compiler"
]

[target.i686-unknown-linux-musl]
pre-build = [
    "apt-get update",
    "apt-get install --assume-yes musl musl-dev musl-tools protobuf-compiler"
]

[target.x86_64-unknown-linux-musl]
pre-build = [
    "apt-get update",
    "apt-get install --assume-yes musl musl-dev musl-tools protobuf-compiler"
]
