# [target.x86_64-unknown-linux-musl]
# pre-build = [
#     "apt-get update",
#     "apt-get install --assume-yes musl musl-dev musl-tools protobuf-compiler"
# ]

[target]
pre-build = [
    "apt-get update",
    "apt-get install --assume-yes musl musl-dev musl-tools protobuf-compiler"
]
